/**
 * Generate-and-insert loop for autogenerated card codes.
 *
 * The uniqueness arbiter is the database's `(tenant_id, code)` unique index,
 * never a prior SELECT: the Neon HTTP driver has no interactive transactions,
 * so a check-then-insert would be racy and would buy nothing. The loop
 * therefore generates a candidate, lets the caller attempt the insert, and
 * reacts to the outcome.
 *
 * Knows nothing about the database — the caller owns the insert **and** the
 * decision of what counts as a taken code.
 */

import {
  MAX_ATTEMPTS_PER_LENGTH,
  MAX_LENGTH,
  MIN_LENGTH,
} from "./constants";
import { generateNumericCode } from "./generate";
import { FIRST_ATTEMPT, nextAttempt, type CodeAttempt } from "./plan";

/**
 * Every candidate code was rejected: the adaptive policy ran from `MIN_LENGTH`
 * to `MAX_LENGTH` without a single insert succeeding.
 *
 * This is a broken-invariant signal, not a retryable condition — at the
 * intended scale it cannot happen by chance.
 */
export class CardCodeExhaustedError extends Error {
  constructor() {
    super(
      `Could not allocate a unique card code: every length from ${MIN_LENGTH} ` +
        `to ${MAX_LENGTH} digits collided ${MAX_ATTEMPTS_PER_LENGTH} times.`,
    );
    this.name = "CardCodeExhaustedError";
  }
}

/**
 * Attempts to persist a row under `code`.
 *
 * Resolves with the created value on success, or `null` when the code is
 * already taken — that is the ONLY signal that means "generate another one".
 * Every other failure must be thrown, so it propagates untouched.
 */
export type TryInsertWithCode<T> = (code: string) => Promise<T | null>;

export interface WithGeneratedCodeOptions {
  /** Code generator. Injectable so tests can make candidates deterministic. */
  generate?: (length: number) => string;
}

/**
 * Run `tryInsert` with freshly generated numeric codes until one is accepted.
 *
 * Attempts are strictly sequential — a candidate is only generated once the
 * previous one is known to be taken.
 *
 * @param tryInsert - Insert attempt; resolves `null` when the code is taken.
 * @param options   - Optional generator injection.
 * @returns Whatever `tryInsert` resolved with on the accepted code.
 * @throws {CardCodeExhaustedError} If the adaptive policy is exhausted.
 */
export async function withGeneratedCode<T>(
  tryInsert: TryInsertWithCode<T>,
  options: WithGeneratedCodeOptions = {},
): Promise<T> {
  const generate = options.generate ?? generateNumericCode;

  let attempt: CodeAttempt | null = FIRST_ATTEMPT;
  while (attempt !== null) {
    const created = await tryInsert(generate(attempt.length));
    if (created !== null) return created;
    attempt = nextAttempt(attempt);
  }

  throw new CardCodeExhaustedError();
}
