/**
 * Card code generation policy.
 *
 * Autogenerated codes are purely numeric strings, unique per tenant. Their
 * length is decided **per code**, never per tenant: every allocation starts at
 * `MIN_LENGTH` and only grows if that length keeps colliding for the card
 * currently being created.
 *
 * The growth is a safety valve, not an expected path. At this product's scale
 * (hundreds to low thousands of cards per tenant) a 5-digit space holds 100 000
 * codes, so `MAX_ATTEMPTS_PER_LENGTH` consecutive collisions at 5 digits is
 * effectively impossible until a tenant is orders of magnitude larger.
 *
 * Deliberately NOT persisted: no "current length" column, no per-card-type
 * configuration. Codes of different lengths coexist without any bookkeeping,
 * which is what makes the policy safe to change later — nothing recorded in the
 * database depends on it.
 */

/** Digits in the first candidate code of every allocation. */
export const MIN_LENGTH = 5;

/**
 * Upper bound on the growth. Reaching it means every length from `MIN_LENGTH`
 * up collided `MAX_ATTEMPTS_PER_LENGTH` times, which is a broken-invariant
 * signal (an exhausted keyspace or a misidentified conflict), not a retry case:
 * allocation throws instead of growing further.
 */
export const MAX_LENGTH = 12;

/**
 * Insert attempts made at a given length before adding a digit. Kept small on
 * purpose: each attempt is a database round trip, and a length that collides
 * this often is better escaped than hammered.
 */
export const MAX_ATTEMPTS_PER_LENGTH = 8;
